### ISSUE TITLE
"lossless" image format is not lossless

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-sdk#311]
## Description

When using `lossless` as an image format, it's expected to be served images which are lossless, but that's not the case for `webp` with the default options.

- RIPE SDK translates `lossless` to `webp` when possible: https://github.com/ripe-tech/ripe-sdk/blob/b0b5300451df6a89725ffc0e30eeaac80a947593/src/js/base/ripe.js#L695
- ripe-compose by default applies lossful compression when using `webp`: https://github.com/ripe-tech/ripe-compose/blob/0ffa265a375e39dceaa2ab853e25e19cf59546f0/src/ripe_compose/util/configurator.py#L84

Example:
- png: https://ripe-core-stage.platforme.com/api/compose?brand=hermes&model=h003572sv01&initials=MARTA&initials_profile=jungle_love,black,zoom&p=body:silk:01&p=shadow:default:default&size=850
- webp: https://ripe-core-stage.platforme.com/api/compose?brand=hermes&model=h003572sv01&initials=MARTA&initials_profile=jungle_love,black,zoom&p=body:silk:01&p=shadow:default:default&size=850&format=webp

**Comment by joamag** [comment]
Let's not be strict here "Lossless == Almost lossless" 😆 
Now seriously nice catch

**Comment by joamag** [comment]
Let's make default webp options lossless and measure the impact in image size, then discuss on this one

**Comment by 3rdvision** [comment]
After a deeper investigation I've come to realize that this could not be fixed by increasing the `quality = 100` (currently at 95) implemented [here](https://github.com/ripe-tech/ripe-compose/blob/0ffa265a375e39dceaa2ab853e25e19cf59546f0/src/ripe_compose/util/configurator.py#L84) - the quality degradation from changing 95 -> 100 looked visually imperceptible to my eyes.

The buggy "blur" effect, mostly evident on the initials "MARTA" is being caused by the python imaging library most specifically the `PIL.WebPImagePlugin` which we use when saving the image composition at [image.save](https://github.com/ripe-tech/ripe-compose/blob/master/src/ripe_compose/util/configurator.py#L3355) for webp format. This WebPImagePlugin has  [lossless at false by default](https://github.com/python-pillow/Pillow/blob/master/src/PIL/WebPImagePlugin.py#L310) and that was the cause of this blur effect.

Below are the image compositions

| - | - |
| --- | --- |
| current webp at 90% quality = 247.27 kb | ![](https://ripe-core-stage.platforme.com/api/compose?brand=hermes&model=h003572sv01&initials=MARTA&initials_profile=jungle_love,black,zoom&p=body:silk:01&p=shadow:default:default&size=850&format=webp) |
| **lossless webp at 95% quality = 913.13 kb** | ![imagem](https://pla1.fra1.digitaloceanspaces.com/ripe_core_now/c9912c5f-2032-4776-9044-0f0ddeaf5016.attachment.compose.webp) |
| **lossless webp at 100% quality = 913.6 kb** | ![imagem](https://pla1.fra1.digitaloceanspaces.com/ripe_core_now/f5b3b739-b589-4113-afb9-7cab4683f45d.attachment.compose.webp) |
| png = 1.27 MB | ![imagem](https://ripe-core-stage.platforme.com/api/compose?brand=hermes&model=h003572sv01&initials=MARTA&initials_profile=jungle_love,black,zoom&p=body:silk:01&p=shadow:default:default&size=850) |

I'm creating a PR for the 2nd option lossless webp at 95% quality = 913.13 kb

**Comment by gcandal** [comment]
https://github.com/ripe-tech/ripe-compose/pull/133#issuecomment-925997082
